/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new user account
         * @description This endpoint takes in the user creation details and returns jwt tokens along with user data
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login a registered user
         * @description This endpoint retrieves the jwt tokens for a registered user
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in or sign up with Google
         * @description Verifies a Google ID token and returns jwt tokens along with user data
         */
        post: operations["google_auth_api_v1_auth_google_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh tokens
         * @description This endpoint uses the current refresh token to create new access and refresh tokens
         */
        post: operations["refresh_tokens_api_v1_auth_token_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user details
         * @description This endpoint retrieves the details of the logged-in user
         */
        get: operations["get_user_api_v1_auth_user_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/google/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Connect Google Sheets
         * @description Exchange the OAuth code for a refresh token and store it for this user
         */
        post: operations["connect_google_sheets_api_v1_export_google_tokens_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/google/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Sheets connection status
         * @description Checks the database only — no Google network call
         */
        get: operations["get_google_export_status_api_v1_export_google_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/google/sheets/{form_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export a form's responses to Google Sheets
         * @description Build rows from the form's responses and create a spreadsheet in the user's Drive
         */
        post: operations["export_form_to_google_sheets_api_v1_export_google_sheets__form_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/google/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disconnect Google Sheets
         * @description Forgets the stored token locally (does not revoke it on Google)
         */
        post: operations["disconnect_google_sheets_api_v1_export_google_disconnect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/csv/{form_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export form responses as CSV
         * @description Download the form's responses as a CSV file (Excel and Sheets compatible)
         */
        get: operations["export_form_to_csv_api_v1_export_csv__form_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List user forms
         * @description Get all forms created by the authenticated user
         */
        get: operations["list_user_forms_api_v1_forms_get"];
        put?: never;
        /**
         * Create a new form
         * @description Create a new form for the authenticated user
         */
        post: operations["create_form_api_v1_forms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forms/{form_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a form
         * @description Get a single form belonging to the authenticated user
         */
        get: operations["get_form_api_v1_forms__form_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete a form
         * @description Delete a single form belonging to the authenticated user
         */
        delete: operations["delete_form_api_v1_forms__form_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update a form
         * @description Update a single form belonging to the authenticated user
         */
        patch: operations["update_form_api_v1_forms__form_id__patch"];
        trace?: never;
    };
    "/api/v1/forms/public/{form_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a public form
         * @description Get a single published form (no authentication required)
         */
        get: operations["get_public_form_api_v1_forms_public__form_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate form questions
         * @description Generate or modify a list of form questions using an LLM based on a user prompt, with conversation memory
         */
        post: operations["generate_questions_api_v1_llm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forms/{form_id}/responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List form responses
         * @description Get all responses for a form (authentication required)
         */
        get: operations["list_form_responses_api_v1_forms__form_id__responses_get"];
        put?: never;
        /**
         * Submit a response
         * @description Submit a response to a public form (no authentication required)
         */
        post: operations["submit_response_api_v1_forms__form_id__responses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forms/{form_id}/responses/{response_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a response
         * @description Get a single response for a form (authentication required)
         */
        get: operations["get_form_response_api_v1_forms__form_id__responses__response_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Root */
        get: operations["get_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Probe */
        get: operations["probe_probe_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthResponse */
        AuthResponse: {
            /** Status Code */
            status_code: number;
            /** Message */
            message: string;
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            data: components["schemas"]["AuthResponseData"];
        };
        /** AuthResponseData */
        AuthResponseData: {
            /** Id */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** FormCreateRequest */
        FormCreateRequest: {
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Questions */
            questions?: components["schemas"]["FormQuestionInput"][] | null;
            /** Conversation Id */
            conversation_id?: string | null;
        };
        /** FormListResponse */
        FormListResponse: {
            /** Status Code */
            status_code: number;
            /** Message */
            message: string;
            /** Data */
            data: components["schemas"]["FormListResponseData"][];
        };
        /** FormListResponseData */
        FormListResponseData: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Is Published */
            is_published: boolean;
            /** User Id */
            user_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** FormQuestion */
        FormQuestion: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /**
             * Answer Type
             * @enum {string}
             */
            answer_type: "text" | "select";
            /** Answer Select Options */
            answer_select_options?: string[] | null;
            /** Answer Select Multiple */
            answer_select_multiple?: boolean | null;
            /** Required */
            required: boolean;
        };
        /**
         * FormQuestionInput
         * @description Adds extra cross field validation
         */
        FormQuestionInput: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /**
             * Answer Type
             * @enum {string}
             */
            answer_type: "text" | "select";
            /** Answer Select Options */
            answer_select_options?: string[] | null;
            /** Answer Select Multiple */
            answer_select_multiple?: boolean | null;
            /** Required */
            required: boolean;
        };
        /** FormResponse */
        "FormResponse-Input": {
            /** Title */
            title: string | null;
            /** Description */
            description: string | null;
            /** Questions */
            questions: components["schemas"]["FormQuestionInput"][];
        };
        /** FormResponseCreateRequest */
        FormResponseCreateRequest: {
            /** Answers */
            answers: components["schemas"]["ResponseAnswerInput"][];
        };
        /** FormResponseListResponse */
        FormResponseListResponse: {
            /** Status Code */
            status_code: number;
            /** Message */
            message: string;
            /** Data */
            data: components["schemas"]["app__features__response__schemas__FormResponseData"][];
        };
        /** FormResponseResponse */
        FormResponseResponse: {
            /** Status Code */
            status_code: number;
            /** Message */
            message: string;
            data: components["schemas"]["app__features__response__schemas__FormResponseData"];
        };
        /** FormUpdateRequest */
        FormUpdateRequest: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Questions */
            questions?: components["schemas"]["FormQuestionInput"][] | null;
            /** Is Published */
            is_published?: boolean | null;
        };
        /** GoogleAuthRequest */
        GoogleAuthRequest: {
            /** Id Token */
            id_token: string;
        };
        /** GoogleConnectData */
        GoogleConnectData: {
            /** Connected */
            connected: boolean;
            /** Google Email */
            google_email?: string | null;
        };
        /** GoogleConnectResponse */
        GoogleConnectResponse: {
            /** Status Code */
            status_code: number;
            /** Message */
            message: string;
            data: components["schemas"]["GoogleConnectData"];
        };
        /** GoogleConnectionStatus */
        GoogleConnectionStatus: {
            /** Connected */
            connected: boolean;
            /** Google Email */
            google_email?: string | null;
        };
        /** GoogleConnectionStatusResponse */
        GoogleConnectionStatusResponse: {
            /** Status Code */
            status_code: number;
            /** Message */
            message: string;
            data: components["schemas"]["GoogleConnectionStatus"];
        };
        /** GoogleDisconnectResponse */
        GoogleDisconnectResponse: {
            /** Status Code */
            status_code: number;
            /** Message */
            message: string;
        };
        /** GoogleSheetsExportData */
        GoogleSheetsExportData: {
            /** Spreadsheet Url */
            spreadsheet_url: string;
        };
        /** GoogleSheetsExportResponse */
        GoogleSheetsExportResponse: {
            /** Status Code */
            status_code: number;
            /** Message */
            message: string;
            data: components["schemas"]["GoogleSheetsExportData"];
        };
        /** GoogleTokenExchangeRequest */
        GoogleTokenExchangeRequest: {
            /** Code */
            code: string;
            /** Code Verifier */
            code_verifier: string;
            /** Redirect Uri */
            redirect_uri: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LLMRequest */
        LLMRequest: {
            /** Prompt */
            prompt: string;
            /** Conversation Id */
            conversation_id?: string | null;
            current_state?: components["schemas"]["FormResponse-Input"] | null;
        };
        /** LLMResponse */
        LLMResponse: {
            /** Status Code */
            status_code: number;
            /** Message */
            message: string;
            data: components["schemas"]["app__features__llm__schemas__FormResponse"];
            /** Conversation Id */
            conversation_id: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Password */
            password: string;
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** ResponseAnswer */
        ResponseAnswer: {
            /** Question Id */
            question_id: string;
            /**
             * Answer Type
             * @enum {string}
             */
            answer_type: "text" | "select";
            /** Text Answer */
            text_answer?: string | null;
            /** Select Answer */
            select_answer?: string[] | null;
        };
        /**
         * ResponseAnswerInput
         * @description Adds cross-field validation
         */
        ResponseAnswerInput: {
            /** Question Id */
            question_id: string;
            /**
             * Answer Type
             * @enum {string}
             */
            answer_type: "text" | "select";
            /** Text Answer */
            text_answer?: string | null;
            /** Select Answer */
            select_answer?: string[] | null;
        };
        /** TokenRefreshRequest */
        TokenRefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** TokenRefreshResponse */
        TokenRefreshResponse: {
            /** Status Code */
            status_code: number;
            /** Message */
            message: string;
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
        };
        /** UserResponse */
        UserResponse: {
            /** Status Code */
            status_code: number;
            /** Message */
            message: string;
            data: components["schemas"]["AuthResponseData"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** FormResponse */
        app__features__form__schemas__FormResponse: {
            /** Status Code */
            status_code: number;
            /** Message */
            message: string;
            data: components["schemas"]["app__features__form__schemas__FormResponseData"];
        };
        /** FormResponseData */
        app__features__form__schemas__FormResponseData: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Questions */
            questions: components["schemas"]["FormQuestion"][] | null;
            /** Is Published */
            is_published: boolean;
            /** Conversation Id */
            conversation_id: string | null;
            /** User Id */
            user_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** FormResponse */
        app__features__llm__schemas__FormResponse: {
            /** Title */
            title: string | null;
            /** Description */
            description: string | null;
            /** Questions */
            questions: components["schemas"]["FormQuestionInput"][];
        };
        /** FormResponseData */
        app__features__response__schemas__FormResponseData: {
            /** Id */
            id: string;
            /** Answers */
            answers: components["schemas"]["ResponseAnswer"][];
            /** Form Id */
            form_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_auth_api_v1_auth_google_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleAuthRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_tokens_api_v1_auth_token_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefreshResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_v1_auth_user_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    connect_google_sheets_api_v1_export_google_tokens_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleTokenExchangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleConnectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_google_export_status_api_v1_export_google_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleConnectionStatusResponse"];
                };
            };
        };
    };
    export_form_to_google_sheets_api_v1_export_google_sheets__form_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleSheetsExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_google_sheets_api_v1_export_google_disconnect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleDisconnectResponse"];
                };
            };
        };
    };
    export_form_to_csv_api_v1_export_csv__form_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_user_forms_api_v1_forms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormListResponse"];
                };
            };
        };
    };
    create_form_api_v1_forms_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FormCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__features__form__schemas__FormResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_form_api_v1_forms__form_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__features__form__schemas__FormResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_form_api_v1_forms__form_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_form_api_v1_forms__form_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FormUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__features__form__schemas__FormResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_public_form_api_v1_forms_public__form_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__features__form__schemas__FormResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_questions_api_v1_llm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LLMRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_form_responses_api_v1_forms__form_id__responses_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormResponseListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_response_api_v1_forms__form_id__responses_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FormResponseCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormResponseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_form_response_api_v1_forms__form_id__responses__response_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form_id: string;
                response_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormResponseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    probe_probe_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
